### ISSUE TITLE
Cannot create new task

### ISSUE THREAD

**Issue by jarrod268** [sandy081/vscode-todotasks#1]
Pressing CTL +1 I receive the error message that there is no handler found for command task.new

**Comment by sandy081** [comment]
Hi @jarrod268 
Can you please provide your Keyboard shortcuts to see if the command is bound or not.

Thanks
Sandeep

**Comment by qwench** [comment]
Same here. vscode 1.2.0.
 - new file
 - F1, todo:new task
 - No Handler found... An extension might be missing an activation event.

**Comment by sandy081** [comment]
@qwench @jarrod268 I think I got this..

This is because these commands are active only on todo files with following extensions
.todo, .tasks

That is why these commands are not running. I will update this in the documentation and close this.

**Comment by qwench** [comment]
Ok, thanks.
You should then display todo commands only on correct file extension.

**Comment by tapir** [comment]
Also you should add this to the description of the addon. It's not clear. Thanks for the great plugin.

**Comment by sandy081** [comment]
I think commands are controlled by VS Code platform.. At present we show all commands, I think showing commands only specific or relevant to a file could be good.. I am not sure but I will check about this.

For now, I am providing following fix
- Todo extension commands does something only on files with proper extension
- Update the documentation with this
