### ISSUE TITLE
built-in tags changes text color

### ISSUE THREAD

**Issue by ujc** [sandy081/vscode-todotasks#11]
when I tag a task using one of the built-in tags such as "@critical" etc, it colors the text for the tag (all ok so far).

**If I then delete the tag (backspace all the way), the text color + background is stuck on the "tag" color, and anything else I type in (including whitespace) gets a dark-orange background with black text.**

what's the right way to remove a tag, so that it doesn't effect the color of it's surrounding text ?

**Comment by sandy081** [comment]
@ujc This looks a bug to me. Will fix this. Thanks for reporting

**Comment by hxlnt** [comment]
Perhaps related: Deleting a @done tag and then creating a new task with Ctrl+Enter results in the following error. 
![snip_20160920123852](https://cloud.githubusercontent.com/assets/9647195/18681849/6676e1f0-7f2f-11e6-8f08-47699b001e5a.png)

**Comment by andresgottlieb** [comment]
Also, deleting a @done tag leaves you with green text forever (it's impossible to go back to normal). There's clearly a big issue with deleting tag-formatted text.

**Comment by sandy081** [comment]
Thanks all for filing the issue... Fixed it and will publish.
