### ISSUE TITLE
When creating a new task, checkbox is selected by default, causing me to delete it

### ISSUE THREAD

**Issue by chrisdias** [sandy081/vscode-todotasks#2]
On a new, empty line press Cmd+1 to create a new task, it looks like this:

![image](https://cloud.githubusercontent.com/assets/1487073/15254694/eb3c77f0-18ec-11e6-96db-83b8337d6cd6.png)

the problem is that the check box and first space are selected.  When I start to type the first few characters of my task, they then get deleted.  To work around this i have to press Cmd+1 and then right arrow.

**Comment by sandy081** [comment]
@chrisdias Yeah this is a nasty bug and has bad user experience. I am aware of this and is in my defect list in todotasks-project.tasks. 

Thanks for filing the issue and fixed this.
