### ISSUE TITLE
Do not steal cmd +1 on mac

### ISSUE THREAD

**Issue by isidorn** [sandy081/vscode-todotasks#4]
VSCode uses the cmd + 1 shortcut for focusing the leftmost editor.
When I install the todo tasks extension this shortcut is being hijacked.

Are there maybe some free shortcuts which could be used instead? Maybe take a look at preferences > keyboard shortcut

**Comment by sandy081** [comment]
@isidorn Cmd + Enter (and Ctrl + Enter in Linux) was the shortcut I started using, but later we wanted to be bit similar to One Note where Cmd + 1 is shortcut for creating a todo task.. But, I can see that,from VS Code point of view this is most known for focussing leftmost editor.

I will make it to use initial short cut and leave Cmd + 1.
